version: "3.7"
services:
  mysql:
    image: mysql:5.7
    volumes:
      - /docker/mysql/data:/var/lib/mysql
      - /docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    restart: always
    container_name: lab-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PWD}

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    restart: always
    container_name: lab-db-gui
    ports:
      - "8080:80"

  web:
    build:
      context: ./docker/php
    ports:
      - 80:80
    privileged: true
    volumes:
      - "./:/var/www/html"
    container_name: "apache"
